import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const [username, setUsername] = useState(null);

  // Check if user session exists
  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("userSession") || "null");
    if (user) {
      setUsername(user.username);
    }
  }, [username]);

  const handleSignout = () => {
    setUsername(null);
    localStorage.removeItem("userSession");
  };

  return (
    <>
      <Head>
        <title>Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-center">
        <nav className="max-h-1/5 navbar navbar-expand-lg navbar-light relative flex w-full flex-wrap items-center justify-around py-4 font-bold shadow-lg">
          <div className="w-1/3">
            {username ? (
              <span>You are signed in as {username}</span>
            ) : (
              <span>You are not signed in</span>
            )}
          </div>
          <h1 className="text-4xl">Calculator App</h1>
          {username ? (
            <div className="flex w-1/3 justify-end">
              <button onClick={() => handleSignout()}>Sign Out</button>
            </div>
          ) : (
            <div className="flex w-1/3 justify-end">
              <Link href="/login">
                <button className="mr-10">Login</button>
              </Link>
              <Link href="/signup">
                <button>Sign Up</button>
              </Link>
            </div>
          )}
        </nav>
        <div className="mt-10 h-[580px] w-[500px] border-4 border-black bg-gray-500">
          <div className="mx-auto mt-5 flex h-[100px] w-[400px] items-center justify-end border-2 border-black bg-slate-400 p-2 text-5xl">
            <span>0</span>
          </div>
          <div className="grid grid-cols-4 gap-[1px] p-5">
            <button className="button bg-red-500 hover:bg-red-600">MC</button>
            <button className="button bg-red-500 hover:bg-red-600">MR</button>
            <button className="button bg-red-500 hover:bg-red-600">M+</button>
            <button className="button bg-red-500 hover:bg-red-600">M-</button>
            <button className="button bg-green-500 hover:bg-green-600">
              AC
            </button>
            <button className="button bg-green-500 hover:bg-green-600">
              %
            </button>
            <button className="button bg-green-500 hover:bg-green-600">
              √
            </button>
            <button className="button bg-green-500 hover:bg-green-600">
              ^
            </button>
            <button className="button bg-sky-500 hover:bg-sky-600">7</button>
            <button className="button bg-sky-500 hover:bg-sky-600">8</button>
            <button className="button bg-sky-500 hover:bg-sky-600">9</button>
            <button className="button bg-orange-500 hover:bg-orange-600">
              /
            </button>
            <button className="button bg-sky-500 hover:bg-sky-600">4</button>
            <button className="button bg-sky-500 hover:bg-sky-600">5</button>
            <button className="button bg-sky-500 hover:bg-sky-600">6</button>
            <button className="button bg-orange-500 hover:bg-orange-600">
              *
            </button>
            <button className="button bg-sky-500 hover:bg-sky-600">1</button>
            <button className="button bg-sky-500 hover:bg-sky-600">2</button>
            <button className="button bg-sky-500 hover:bg-sky-600">3</button>
            <button className="button bg-orange-500 hover:bg-orange-600">
              -
            </button>
            <button className="button bg-sky-500 hover:bg-sky-600">0</button>
            <button className="button bg-sky-500 hover:bg-sky-600">.</button>
            <button className="button bg-sky-500 hover:bg-sky-600">=</button>
            <button className="button bg-orange-500 hover:bg-orange-600">
              +
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
