import Head from "next/head";
import { useState } from "react";

export default function Signup() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  return (
    <>
      <Head>
        <title>Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-start justify-center bg-slate-300 pt-10">
        <div className="w-1/3 bg-white px-10 py-5">
          <h3 className="text-center text-3xl font-bold">Signup</h3>
          <form>
            <input
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="mt-5 block w-full rounded-lg border-2 border-solid border-slate-200 p-2 focus:border-slate-500 focus:outline-none"
            />
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="mt-5 block w-full rounded-lg border-2 border-solid border-slate-200 p-2 focus:border-slate-500 focus:outline-none"
            />
            <div className="flex justify-center pt-5">
              <button className="w-1/4 rounded-lg bg-blue-500 p-4 font-bold text-white hover:cursor-pointer hover:bg-blue-700">
                Sign Up
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
